spring:
  application:
    name: eureka
server:
  port: 1021
eureka:
  instance:
    appname: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://localhost:1020/eureka/,http://localhost:1021/eureka/,http://localhost:1022/eureka/,http://localhost:1033/eureka/
  server:
    eviction-interval-timer-in-ms: 30000  #检测失效信息的时间
    enable-self-preservation: false  #关闭自我保护
    use-read-only-response-cache: false
