spring:
  application:
    name: provider
server:
  port: 2020
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1020/eureka/,http://localhost:1021/eureka/,http://localhost:1022/eureka/
  instance:
    appname: ${spring.application.name}
    prefer-ip-address: true
